recomendacion_area_1 = "ÁREA I: ADMINISTRACION - ECONOMIA - NEGOCIOS\n\nCARRERAS UNIVERSITARIAS:\n- CONTADOR PUBLICO\n- LIC EN ADMINISTRACION DE NEGOCIOS\n- LIC. EN ADMINISTRACION AGRARIA / RURAL"
recomendacion_area_2 = "quimico"
